import React, { createContext, useContext, useState, useEffect } from 'react';
import { I18nManager } from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';

export type Language = 'ar' | 'fr' | 'en';

const LANGUAGE_KEY = 'snapschool_app_language';

const translations = {
  ar: {
    tabHome: "الرئيسية",
    tabCourses: "المواد",
    tabAnnouncements: "الإعلانات",
    tabPayments: "المدفوعات",
    tabProfile: "حسابي",
    loading: "جاري التحميل...",
    switchChild: "تغيير التلميذ",
    todaysSchedule: "جدول اليوم",
    history: "السجل",
    noClasses: "لا توجد دروس اليوم",
    freeDay: "اليوم راحة، نتمنى لك يوماً سعيداً!",
    tasks: "مهام",
    allCaughtUp: "ممتاز! تم إنجاز جميع الواجبات.",
    teacherRemarks: "ملاحظات وتوصيات المعلمين",
    noRemarks: "لا توجد ملاحظات جديدة اليوم.",
    quickActions: "وصول سريع",
    examCenter: "مركز الامتحانات",
    examCenterSub: "مواعيد وجدول الامتحانات",
    reportCard: "دفتر الأعداد والنتائج",
    reportCardSub: "المعدلات والملاحظات",
    backToToday: "العودة لليوم",
    absent: "غائب",
    present: "حاضر",
    late: "متأخر",
    upcoming: "قادم",
    teacher: "المدرس",
    academicPortal: "الفضاء المدرسي",
    coursesHub: "المواد والدروس",
    coursesSub: "الدروس والوثائق الخاصة بـ",
    filesCount: "وثائق",
    viewLearningMaterials: "عرض الوثائق والدروس",
    noCourses: "لا توجد مواد مسجلة حالياً",
    noCoursesSub: "ستظهر الوثائق والدروس هنا فور تنزيلها من قبل المعلم.",
    academicSpace: "الفضاء المدرسي",
    coursesTitle: "المواد الدراسية",
    results: "الأعداد والنتائج",
    attendance: "المواظبة والحضور",
    exams: "جدول الامتحانات",
    noExams: "لا توجد امتحانات مبرمجة حالياً",
    documents: "وثائق ومستندات",
    documentsCenter: "مركز الوثائق",
    trimester1: "الثلاثي الأول",
    trimester2: "الثلاثي الثاني",
    trimester3: "الثلاثي الثالث",
    paymentsTitle: "الرسوم والمدفوعات",
    totalOutstanding: "المبلغ الجملي المستحق",
    currencyTnd: "د.ت",
    filterAll: "الكل",
    filterPaid: "المستخلصة",
    filterUnpaid: "غير المستخلصة",
    paymentHistory: "جدول الأقساط والمدفوعات",
    tuitionFees: "قسط التسجيل والدراسة",
    overdueBadge: "متأخر",
    overdueDays: "مستحق منذ",
    daysLabel: "يوم",
    receipts: "وصولات الخلاص",
    paid: "خلاص تام",
    pending: "قيد الانتظار",
    totalPaid: "المبلغ المدفوع",
    remaining: "المتبقي",
    downloadReceipt: "تحميل الوصل (PDF)",
    announcementsTitle: "إعلانات المدرسة",
    schoolNews: "أخبار وإعلانات الإدارة",
    schoolNewsBadge: "أخبار المدرسة",
    urgentBadge: "عاجل",
    readMore: "قراءة التفاصيل",
    profileTitle: "الملف الشخصي",
    profileSettingTitle: "إعدادات الملف الشخصي",
    myChildren: "أبنائي المسجلين",
    generalSection: "إعدادات عامة",
    preferencesSection: "التفضيلات واللغة",
    editProfileItem: "تعديل الملف الشخصي",
    editProfileSub: "تحديث الصورة، الاسم، ورقم الهاتف",
    reportCardItem: "دفتر الأعداد والنتائج",
    profileReportCardSub: "متابعة نتائج ومعدلات التلميذ",
    documentCenterItem: "مركز الوثائق والمستندات",
    profileDocumentCenterSub: "تحميل الوثائق الإدارية والشهائد",
    notificationsItem: "التنبيهات والإشعارات",
    notificationsSub: "تعديل وتخصيص تفضيلات التنبيهات",
    schoolSupportItem: "الدعم والتواصل مع المدرسة",
    schoolSupportSub: "الاتصال المباشر بإدارة المؤسسة",
    signOutSub: "تسجيل الخروج الآمن من الحساب",
    classLabel: "القسم",
    cancel: "إلغاء",
    save: "حفظ",
    appLanguage: "لغة التطبيق",
    arabic: "العربية 🇹🇳",
    french: "Français 🇫🇷",
    english: "العربية 🇹🇳",
    signOut: "تسجيل الخروج",
    linkChild: "ربط تلميذ جديد",
    selectLanguageTitle: "اختر لغة التطبيق",
    confirm: "تأكيد",
    monday: "الإثنين",
    tuesday: "الثلاثاء",
    wednesday: "الأربعاء",
    thursday: "الخميس",
    friday: "الجمعة",
    saturday: "السبت",
    sunday: "الأحد",
    jan: "يناير",
    feb: "فبراير",
    mar: "مارس",
    apr: "أبريل",
    may: "ماي",
    jun: "جوان",
    jul: "جويلية",
    aug: "أوت",
    sep: "سبتمبر",
    oct: "أكتوبر",
    nov: "نوفمبر",
    dec: "ديسمبر",
    teacherMySchedule: "جدولي",
    teacherTasks: "المهام",
    teacherClasses: "الأقسام",
    teacherUpcomingClasses: "الحصص القادمة",
    teacherNoClassesToday: "لا توجد حصص مبرمجة اليوم",
    teacherMarkAttendance: "تسجيل الحضور",
    teacherViewTasks: "عرض المهام",
    teacherQuickActions: "إجراءات سريعة",
    teacherClassesRoster: "الأقسام · قائمة التلاميذ",
    teacherAllClasses: "كل الأقسام",
    teacherActiveClasses: "أقسام نشطة",
    teacherStudentsTotal: "تلميذ",
    teacherLessons: "دروس",
    teacherNoClassesFound: "لا توجد أقسام",
    teacherClassRoster: "قائمة التلاميذ",
    teacherStudent: "تلميذ",
    teacherStudents: "تلاميذ",
    teacherAttendance: "الحضور",
    teacherGrades: "الأعداد",
    teacherContact: "اتصال",
    teacherTakeAttendance: "أخذ الحضور",
    teacherPresent: "حاضر",
    teacherAbsent: "غائب",
    teacherLate: "متأخر",
    teacherMarkAllPresent: "الكل حاضر",
    teacherSubmitAttendance: "تسجيل الحضور",
    teacherTotalStudents: "مجموع التلاميذ",
    teacherAttendanceSummary: "الملخص",
    teacherLessonsContent: "الدروس والمحتوى",
    teacherUploadLesson: "رفع درس",
    teacherFiles: "ملفات",
    teacherDelete: "حذف",
    teacherAddDocument: "إضافة وثيقة",
    teacherClassTasks: "مهام القسم",
    teacherPending: "قيد الانتظار",
    teacherGraded: "تم التقييم",
    teacherNoTasksFound: "لا توجد مهام",
    teacherAddTask: "إضافة مهمة",
    teacherDue: "تاريخ التسليم",
    teacherTaskDetails: "تفاصيل المهمة",
    teacherDescription: "الوصف",
    teacherAttachments: "المرفقات",
    teacherSubmissions: "التسليمات",
    teacherGrade: "العدد",
    teacherNoSubmissionsYet: "لم يتم التسليم بعد",
    teacherSubmissionReview: "مراجعة التسليم",
    teacherStudentWork: "عمل التلميذ",
    teacherAddFeedback: "إضافة ملاحظة",
    teacherNoFilesAttached: "لا توجد ملفات مرفقة",
    teacherGradeStudent: "إسناد عدد للتلميذ",
    teacherEnterGrade: "أدخل العدد",
    teacherMax20: "أقصى حد 20",
    teacherSaveGrade: "حفظ العدد",
    teacherQuickAssistants: "مساعدات سريعة",
    teacherOutOf20: "من 20",
    teacherResetGrade: "إعادة ضبط",
    welcome: "مرحباً بكم",
    pleaseSelectYourProfileTo: "اختر حسابك للمتابعة والدخول للتطبيق",
    parent: "ولي الأمر",
    monitorProgressGradesAndSchool: "متابعة أعداد ومواظبة وجدول الأبناء",
    manageLessonsAttendanceAndStudent: "إدارة الدروس والواجبات والغيابات",
    student: "التلميذ",
    permissionsRequired: "التنبيهات مغلقة",
    pleaseEnablePushNotificationPermissions: "يرجى تفعيل التنبيهات من إعدادات الهاتف لتصلك التحديثات",
    ok: "حسناً",
    notificationsEnabled: "تم تفعيل التنبيهات 🔔",
    youWillNowReceiveInstant: "ستصلك التنبيهات المباشرة بالواجبات والنتائج والأخبار الرسمية",
    ok1: "تم",
    notificationsDisabled: "تم إيقاف التنبيهات",
    pushNotificationsHaveBeenDisabled: "تم إيقاف الإشعارات المباشرة من التطبيق",
    ok2: "حسناً",
    pleaseEnterYourPhoneNumber: "الرجاء إدخال رقم الهاتف",
    welcomeBack: "مرحباً بك مجدداً!",
    createYourPassword: "أنشئ كلمة السر",
    enterYourRegisteredPhoneNumber: "أدخل رقم الهاتف المسجل لدى المدرسة",
    chooseAStrongPasswordFor: "اختر كلمة سر قوية للدخول إلى حسابك",
    continue: "متابعة",
    setPassword: "حفظ كلمة السر",
    signIn: "تسجيل الدخول",
    parentPortal: "فضاء الأولياء",
    teacherPortal: "فضاء المعلمين",
    accountNotFoundPleaseContact: "الحساب غير موجود",
    networkErrorPleaseTryAgain: "خطأ في الاتصال بالشبكة",
    pleaseEnterYourPassword: "الرجاء إدخال كلمة السر",
    passwordSetPleaseSignIn: "تم إنشاء كلمة السر! تفضل بتسجيل الدخول.",
    accountResetByAdminPlease: "يرجى اختيار كلمة سر جديدة للحساب",
    authenticationFailedPleaseCheckYour: "فشل تسجيل الدخول. تحقق من الاتصال",
    eg55666777: "مثال: 55 666 777",
    createAStrongPassword: "كلمة سر جديدة",
    yourPassword: "كلمة السر",
    accountManagementHandledBySnapschool: "إدارة وتوثيق الحسابات تتم بالتنسيق مع إدارة المدرسة",
    submission: "التسليم",
    completed: "مكتمل",
    submitted: "تم التسليم",
    at: "في",
    workSubmitted: "العمل المُسلّم",
    pdfDocument: "مستند PDF",
    tapToExpand: "انقر للتكبير",
    noPhotoSubmitted: "لم يتم تسليم صورة",
    participationScore: "نقاط المشاركة",
    quickTags: "إشارات سريعة",
    addADetailedNote: "أضف ملاحظة تفصيلية...",
    selectClass: "اختر القسم",
    tapToSwitch: "انقر للتغيير",
    selectSession: "اختر الحصة",
    assignATask: "تعيين مهمة",
    forTheWholeClass: "لكامل القسم",
    taskTitle: "عنوان المهمة",
    descriptionOptional: "وصف (اختياري)",
    addImage: "إضافة صورة",
    addPdf: "إضافة ملف",
    assignedTasks: "المهام المعينة",
    saveChanges: "حفظ التغييرات",
    switchClass: "تغيير القسم",
    selectSession1: "اختر الحصة",
    noStudents: "لا يوجد تلاميذ",
    variousSubjects: "مواد مختلفة",
    searchClassesOrStudents: "بحث عن قسم أو تلميذ...",
    gradeEntry: "إدخال الدرجات",
    selectClassToRecordEvaluations: "حدد فصلا لتسجيل التقييمات",
    yourClasses: "فصولك",
    available: "متاح",
    noClassesAssigned: "لم يتم تعيين فصول",
    studentsEnrolled: "طلاب مسجلين",
    selectSubjectTerm: "حدد المادة والفصل الدراسي",
    selectTerm: "حدد الفصل الدراسي",
    availableSubjects: "المواد المتاحة",
    gradeEntry1: "إدخال الدرجات",
    graded: "مقيّم",
    quickDecimalAssistant: "مساعد الأعشار السريع",
    clear: "مسح",
    gradeSheetProofOptional: "إثبات كشف الدرجات (اختياري)",
    proofImageAttached: "صورة الإثبات مرفقة",
    camera: "كاميرا",
    gallery: "المعرض",
    saveGrades: "حفظ الدرجات",
    enus: "ar-TN",
    goodMorning: "صباح الخير 👋",
    seeAll: "عرض الكل",
    room: "قاعة",
    completed1: "مكتمل",
    live: "مباشر",
    enus1: "ar-SA",
    selectClass1: "اختر القسم",
    tapToSwitch1: "انقر للتغيير",
    addMaterial: "إضافة مادة",
    title: "العنوان *",
    egChapter3Notes: "مثال: ملاحظات الفصل 3",
    subject: "المادة *",
    targetClass: "القسم المستهدف",
    descriptionOptional1: "الوصف (اختياري)",
    briefDescriptionOfThisMaterial: "وصف موجز للمادة...",
    attachFilesOrImages: "إرفاق ملفات أو صور",
    uploadShare: "رفع ومشاركة",
    allSubjects: "كل المواد",
    noMaterialsYet: "لا يوجد مواد بعد",
    uploadPdfsNotesOrLinks: "قم برفع ملفات PDF، ملاحظات، أو روابط ليتمكن تلاميذك من الوصول إليها.",
    addMaterial1: "إضافة مادة",
    file: "ملف",
    files: "ملفات",
    switchClass1: "تغيير القسم",
    filterBySubject: "تصفية حسب المادة",
    overallProgress: "التقدم الإجمالي",
    completed2: "مكتملة",
    noSubmissionsYet: "لا يوجد تسليمات بعد",
    taskDetailsAttachments: "تفاصيل المهمة والمرفقات",
    noDescriptionProvided: "لم يتم توفير وصف",
    photoAttached: "صورة مرفقة",
    documentAttached: "مستند مرفق",
    noAttachments: "لا يوجد مرفقات",
    submissions: "التسليمات",
    students: "تلاميذ",
    completed3: "مكتملة",
    createNewTask: "إنشاء مهمة جديدة",
    title1: "العنوان",
    egMathQuizHistoryEssay: "مثال: اختبار رياضيات",
    description: "الوصف",
    detailsAboutTheTask: "تفاصيل المهمة...",
    class: "القسم",
    attachments: "المرفقات",
    addImagesMax5: "إضافة صور (كحد أقصى 5)",
    createTask: "إنشاء المهمة",
    selectClass2: "اختر القسم",
    tapToSwitch2: "انقر للتغيير",
    noActiveTasksFound: "لا يوجد مهام نشطة",
    switchClass2: "تغيير القسم",
    standard: "قياسي",
    lateWord: "متأخر",
    absentWord: "غائب",
    presentWord: "حاضر",
    markedAs: "تم تسجيله كـ",
    forWord: "في مادة",
    notifPaymentAlert: "تنبيه الدفع",
    notifNewAssignment: "مهمة جديدة",
    notifSchoolAnnouncement: "إعلان مدرسي",
    deleteBtn: "حذف",
    notifAbsences: "الغيابات",
    older: "أقدم",
    today: "اليوم",
    yesterday: "الأمس",
    notificationsScreenTitle: "الإشعارات",
    markAllAsRead: "تحديد الكل كمقروء",
    filterUnread: "غير مقروء",
    filterUrgent: "عاجل",
    notifDefaultTitle: "إشعار",
    notifTeacherRemark: "ملاحظة المعلم",
    notifAttendanceUpdate: "تحديث الحضور",
    completedTask: "مكتمل",
    pendingTask: "قيد الانتظار",
  },
  fr: {
    tabHome: "Accueil",
    tabCourses: "Matières",
    tabAnnouncements: "Annonces",
    tabPayments: "Paiements",
    tabProfile: "Profil",
    loading: "Chargement...",
    switchChild: "Changer d'élève",
    todaysSchedule: "Emploi du Temps",
    history: "Historique",
    noClasses: "Aucun cours aujourd'hui",
    freeDay: "Journée libre ! Profitez-en pour réviser.",
    tasks: "tâches",
    allCaughtUp: "Bravo ! Tout est à jour.",
    teacherRemarks: "Remarques des Enseignants",
    noRemarks: "Aucune remarque aujourd'hui.",
    quickActions: "Accès Rapide",
    examCenter: "Centre d'Examens",
    examCenterSub: "Dates & plannings",
    reportCard: "Bulletin Scolaire",
    reportCardSub: "Moyennes & notes",
    backToToday: "Aujourd'hui",
    absent: "Absent",
    present: "Présent",
    late: "En retard",
    upcoming: "À venir",
    teacher: "Enseignant",
    academicPortal: "Portail Académique",
    coursesHub: "Matières & Cours",
    coursesSub: "Cours et documents pour",
    filesCount: "fichiers",
    viewLearningMaterials: "Voir les cours & supports",
    noCourses: "Aucune matière inscrite",
    noCoursesSub: "Les cours apparaîtront dès qu'ils seront mis en ligne par l'enseignant.",
    academicSpace: "Espace Académique",
    coursesTitle: "Matières & Cours",
    results: "Bulletins & Notes",
    attendance: "Présence & Absences",
    exams: "Planning d'Examens",
    noExams: "Aucun examen programmé pour le moment",
    documents: "Documents",
    documentsCenter: "Centre de Documents",
    trimester1: "1er Trimestre",
    trimester2: "2ème Trimestre",
    trimester3: "3ème Trimestre",
    paymentsTitle: "Frais de Scolarité",
    totalOutstanding: "Total Reste à Payer",
    currencyTnd: "TND",
    filterAll: "Tous",
    filterPaid: "Payés",
    filterUnpaid: "Non Payés",
    paymentHistory: "Historique des Paiements",
    tuitionFees: "Frais de Scolarité",
    overdueBadge: "En Retard",
    overdueDays: "En retard de",
    daysLabel: "jours",
    receipts: "Reçus de Paiement",
    paid: "Payé",
    pending: "En attente",
    totalPaid: "Total Payé",
    remaining: "Reste à payer",
    downloadReceipt: "Télécharger le reçu (PDF)",
    announcementsTitle: "Annonces de l'École",
    schoolNews: "Actualités & Communiqués",
    schoolNewsBadge: "Info École",
    urgentBadge: "Urgent",
    readMore: "Lire la suite",
    profileTitle: "Profil & Réglages",
    profileSettingTitle: "Réglages du Profil",
    myChildren: "Mes Enfants Inscrits",
    generalSection: "Général",
    preferencesSection: "Préférences & Langue",
    editProfileItem: "Modifier le Profil",
    editProfileSub: "Changer photo, nom et numéro",
    reportCardItem: "Bulletin Scolaire",
    profileReportCardSub: "Voir les notes et moyennes",
    documentCenterItem: "Centre de Documents",
    profileDocumentCenterSub: "Télécharger les documents scolaires",
    notificationsItem: "Notifications",
    notificationsSub: "Gérer les préférences d'alertes",
    schoolSupportItem: "Support de l'École",
    schoolSupportSub: "Contacter l'administration",
    signOutSub: "Déconnexion sécurisée",
    classLabel: "Classe",
    cancel: "Annuler",
    save: "Enregistrer",
    appLanguage: "Langue de l'application",
    arabic: "العربية 🇹🇳",
    french: "Français 🇫🇷",
    english: "Français 🇫🇷",
    signOut: "Déconnexion",
    linkChild: "Lier un autre enfant",
    selectLanguageTitle: "Choisir la langue",
    confirm: "Confirmer",
    monday: "Lun",
    tuesday: "Mar",
    wednesday: "Mer",
    thursday: "Jeu",
    friday: "Ven",
    saturday: "Sam",
    sunday: "Dim",
    jan: "Janv",
    feb: "Févr",
    mar: "Mars",
    apr: "Avril",
    may: "Mai",
    jun: "Juin",
    jul: "Juil",
    aug: "Août",
    sep: "Sept",
    oct: "Oct",
    nov: "Nov",
    dec: "Déc",
    teacherMySchedule: "Mon Emploi du Temps",
    teacherTasks: "Tâches",
    teacherClasses: "Classes",
    teacherUpcomingClasses: "Cours à venir",
    teacherNoClassesToday: "Aucun cours prévu aujourd'hui",
    teacherMarkAttendance: "Faire l'appel",
    teacherViewTasks: "Voir les tâches",
    teacherQuickActions: "Actions Rapides",
    teacherClassesRoster: "Classes · Liste des élèves",
    teacherAllClasses: "Toutes les Classes",
    teacherActiveClasses: "classes actives",
    teacherStudentsTotal: "élèves au total",
    teacherLessons: "leçons",
    teacherNoClassesFound: "Aucune classe trouvée",
    teacherClassRoster: "Liste des élèves",
    teacherStudent: "Élève",
    teacherStudents: "Élèves",
    teacherAttendance: "Présence",
    teacherGrades: "Notes",
    teacherContact: "Contact",
    teacherTakeAttendance: "Faire l'appel",
    teacherPresent: "Présent",
    teacherAbsent: "Absent",
    teacherLate: "En retard",
    teacherMarkAllPresent: "Marquer tous présents",
    teacherSubmitAttendance: "Valider l'appel",
    teacherTotalStudents: "Total des élèves",
    teacherAttendanceSummary: "Résumé",
    teacherLessonsContent: "Leçons & Contenu",
    teacherUploadLesson: "Ajouter une leçon",
    teacherFiles: "Fichiers",
    teacherDelete: "Supprimer",
    teacherAddDocument: "Ajouter un document",
    teacherClassTasks: "Tâches de la classe",
    teacherPending: "En attente",
    teacherGraded: "Noté",
    teacherNoTasksFound: "Aucune tâche trouvée",
    teacherAddTask: "Ajouter une tâche",
    teacherDue: "À rendre le",
    teacherTaskDetails: "Détails de la tâche",
    teacherDescription: "Description",
    teacherAttachments: "Pièces jointes",
    teacherSubmissions: "Remises",
    teacherGrade: "Note",
    teacherNoSubmissionsYet: "Aucune remise pour le moment",
    teacherSubmissionReview: "Évaluation de la remise",
    teacherStudentWork: "Travail de l'élève",
    teacherAddFeedback: "Ajouter un commentaire",
    teacherNoFilesAttached: "Aucun fichier joint",
    teacherGradeStudent: "Noter l'élève",
    teacherEnterGrade: "Saisir la note",
    teacherMax20: "Max 20",
    teacherSaveGrade: "Enregistrer la note",
    teacherQuickAssistants: "Saisie rapide",
    teacherOutOf20: "sur 20",
    teacherResetGrade: "Réinitialiser",
    welcome: "Bienvenue",
    pleaseSelectYourProfileTo: "Sélectionnez votre profil pour continuer",
    parent: "Parent",
    monitorProgressGradesAndSchool: "Suivi des notes, absences et emplois du temps",
    manageLessonsAttendanceAndStudent: "Gestion des cours, absences et devoirs",
    student: "Élève",
    permissionsRequired: "Permissions Required",
    pleaseEnablePushNotificationPermissions: "Please enable push notification permissions in system settings to receive alerts.",
    ok: "OK",
    notificationsEnabled: "Notifications Enabled 🔔",
    youWillNowReceiveInstant: "You will now receive instant push alerts for homework, grades, and school news.",
    ok1: "OK",
    notificationsDisabled: "Notifications Disabled",
    pushNotificationsHaveBeenDisabled: "Push notifications have been disabled.",
    ok2: "OK",
    pleaseEnterYourPhoneNumber: "Veuillez saisir votre numéro",
    welcomeBack: "Bienvenue !",
    createYourPassword: "Créez votre mot de passe",
    enterYourRegisteredPhoneNumber: "Entrez votre numéro de téléphone",
    chooseAStrongPasswordFor: "Choisissez un mot de passe sécurisé",
    continue: "Continuer",
    setPassword: "Créer mot de passe",
    signIn: "Se connecter",
    parentPortal: "ESPACE PARENTS",
    teacherPortal: "ESPACE ENSEIGNANTS",
    accountNotFoundPleaseContact: "Account not found. Please contact support.",
    networkErrorPleaseTryAgain: "Network error. Please try again.",
    pleaseEnterYourPassword: "Please enter your password.",
    passwordSetPleaseSignIn: "Password set! Please sign in.",
    accountResetByAdminPlease: "Account reset by admin. Please choose a new password.",
    authenticationFailedPleaseCheckYour: "Authentication failed. Please check your connection.",
    eg55666777: "e.g. 55 666 777",
    createAStrongPassword: "Create a strong password",
    yourPassword: "Your password",
    accountManagementHandledBySnapschool: "Account management handled by SnapSchool Admin.",
    submission: "Soumission",
    completed: "Terminé",
    submitted: "Soumis",
    at: "à",
    workSubmitted: "Travail soumis",
    pdfDocument: "Document PDF",
    tapToExpand: "Appuyez pour agrandir",
    noPhotoSubmitted: "Aucune photo soumise",
    participationScore: "Note de participation",
    quickTags: "Tags rapides",
    addADetailedNote: "Ajouter une note détaillée...",
    selectClass: "Sélectionner la classe",
    tapToSwitch: "Appuyer pour changer",
    selectSession: "Sélectionner une séance",
    assignATask: "Attribuer une tâche",
    forTheWholeClass: "Pour toute la classe",
    taskTitle: "Titre de la tâche",
    descriptionOptional: "Description (optionnel)",
    addImage: "Ajouter une image",
    addPdf: "Ajouter PDF",
    assignedTasks: "Tâches assignées",
    saveChanges: "Sauvegarder les modifications",
    switchClass: "Changer de classe",
    selectSession1: "Sélectionner une séance",
    noStudents: "Aucun élève",
    variousSubjects: "Matières diverses",
    searchClassesOrStudents: "Rechercher des classes ou des élèves...",
    gradeEntry: "Saisie des notes",
    selectClassToRecordEvaluations: "Sélectionner une classe pour enregistrer les évaluations",
    yourClasses: "Vos classes",
    available: "Disponible(s)",
    noClassesAssigned: "Aucune classe attribuée",
    studentsEnrolled: "étudiants inscrits",
    selectSubjectTerm: "Sélectionner la matière et le trimestre",
    selectTerm: "Sélectionner le trimestre",
    availableSubjects: "Matières disponibles",
    gradeEntry1: "Saisie des notes",
    graded: "noté(s)",
    quickDecimalAssistant: "Assistant décimal rapide",
    clear: "Effacer",
    gradeSheetProofOptional: "Preuve de la feuille de notes (Optionnel)",
    proofImageAttached: "Image de preuve jointe",
    camera: "Caméra",
    gallery: "Galerie",
    saveGrades: "Enregistrer les notes",
    enus: "fr-FR",
    goodMorning: "Bonjour 👋",
    seeAll: "Voir tout",
    room: "Salle",
    completed1: "Terminé",
    live: "En cours",
    enus1: "fr-FR",
    selectClass1: "Sélectionner la classe",
    tapToSwitch1: "Appuyer pour changer",
    addMaterial: "Ajouter du matériel",
    title: "Titre *",
    egChapter3Notes: "ex. Notes du Chapitre 3",
    subject: "Matière *",
    targetClass: "Classe cible",
    descriptionOptional1: "Description (optionnel)",
    briefDescriptionOfThisMaterial: "Brève description du matériel...",
    attachFilesOrImages: "Joindre des fichiers ou des images",
    uploadShare: "Télécharger et partager",
    allSubjects: "Toutes les matières",
    noMaterialsYet: "Aucun matériel pour le moment",
    uploadPdfsNotesOrLinks: "Téléchargez des PDF, des notes ou des liens pour que vos élèves y accèdent.",
    addMaterial1: "Ajouter du matériel",
    file: "fichier",
    files: "fichiers",
    switchClass1: "Changer de classe",
    filterBySubject: "Filtrer par matière",
    overallProgress: "Progrès global",
    completed2: "terminé",
    noSubmissionsYet: "Aucune soumission pour le moment",
    taskDetailsAttachments: "Détails de la tâche et pièces jointes",
    noDescriptionProvided: "Aucune description fournie",
    photoAttached: "Photo jointe",
    documentAttached: "Document joint",
    noAttachments: "Aucune pièce jointe",
    submissions: "Soumissions",
    students: "élèves",
    completed3: "terminé",
    createNewTask: "Créer une nouvelle tâche",
    title1: "Titre",
    egMathQuizHistoryEssay: "ex. Quiz de mathématiques",
    description: "Description",
    detailsAboutTheTask: "Détails sur la tâche...",
    class: "Classe",
    attachments: "Pièces jointes",
    addImagesMax5: "Ajouter des images (Max 5)",
    createTask: "Créer la tâche",
    selectClass2: "Sélectionner la classe",
    tapToSwitch2: "Appuyer pour changer",
    noActiveTasksFound: "Aucune tâche active trouvée",
    switchClass2: "Changer de classe",
    standard: "Standard",
    lateWord: "En retard",
    absentWord: "Absent",
    presentWord: "Présent",
    markedAs: "marqué comme",
    forWord: "pour",
    notifPaymentAlert: "Alerte de paiement",
    notifNewAssignment: "Nouveau devoir",
    notifSchoolAnnouncement: "Annonce de l'école",
    deleteBtn: "Supprimer",
    notifAbsences: "Absences",
    older: "Plus ancien",
    today: "Aujourd'hui",
    yesterday: "Hier",
    notificationsScreenTitle: "Notifications",
    markAllAsRead: "Tout marquer comme lu",
    filterUnread: "Non lus",
    filterUrgent: "Urgent",
    notifDefaultTitle: "Notification",
    notifTeacherRemark: "Remarque du professeur",
    notifAttendanceUpdate: "Mise à jour de présence",
    completedTask: "Terminé",
    pendingTask: "À faire",
  },
  en: {
    tabHome: "Home",
    tabCourses: "Courses",
    tabAnnouncements: "Announcements",
    tabPayments: "Payments",
    tabProfile: "Profile",
    loading: "Loading...",
    switchChild: "Switch Student",
    todaysSchedule: "Today's Schedule",
    history: "History",
    noClasses: "No classes today",
    freeDay: "Enjoy your free day and catch up on reading!",
    tasks: "tasks",
    allCaughtUp: "All caught up! No tasks due.",
    teacherRemarks: "Teacher Remarks",
    noRemarks: "No remarks for today.",
    quickActions: "Quick Actions",
    examCenter: "Exam Center",
    examCenterSub: "Dates & schedules",
    reportCard: "Report Card",
    reportCardSub: "Grades & averages",
    backToToday: "Back to Today",
    absent: "Absent",
    present: "Present",
    late: "Late",
    upcoming: "Upcoming",
    teacher: "Teacher",
    academicPortal: "Academic Portal",
    coursesHub: "Courses Hub",
    coursesSub: "Materials and lessons for",
    filesCount: "Files",
    viewLearningMaterials: "View learning materials",
    noCourses: "No active courses",
    noCoursesSub: "Course materials will appear here once your teacher uploads them.",
    academicSpace: "Academic Space",
    coursesTitle: "Courses",
    results: "Results & Marks",
    attendance: "Attendance",
    exams: "Exam Schedule",
    noExams: "No exams scheduled currently",
    documents: "Documents",
    documentsCenter: "Document Center",
    trimester1: "1st Term",
    trimester2: "2nd Term",
    trimester3: "3rd Term",
    paymentsTitle: "Tuition & Fees",
    totalOutstanding: "Total Outstanding",
    currencyTnd: "TND",
    filterAll: "All",
    filterPaid: "Paid",
    filterUnpaid: "Unpaid",
    paymentHistory: "Payment History",
    tuitionFees: "Tuition Fees",
    overdueBadge: "Overdue",
    overdueDays: "Overdue by",
    daysLabel: "days",
    receipts: "Payment Receipts",
    paid: "Paid",
    pending: "Pending",
    totalPaid: "Total Paid",
    remaining: "Remaining",
    downloadReceipt: "Download Receipt (PDF)",
    announcementsTitle: "School Announcements",
    schoolNews: "News & Bulletins",
    schoolNewsBadge: "School News",
    urgentBadge: "Urgent",
    readMore: "Read Details",
    profileTitle: "Profile & Settings",
    profileSettingTitle: "Profile Setting",
    myChildren: "My Enrolled Children",
    generalSection: "General",
    preferencesSection: "Preferences & Language",
    editProfileItem: "Edit Profile",
    editProfileSub: "Change profile picture, number, name",
    reportCardItem: "Report Card",
    profileReportCardSub: "View student academic performance",
    documentCenterItem: "Document Center",
    profileDocumentCenterSub: "Securely access school documents",
    notificationsItem: "Notification",
    notificationsSub: "Customize your notification preferences",
    schoolSupportItem: "School Support",
    schoolSupportSub: "Official SnapSchool Help",
    signOutSub: "Securely log out of Account",
    classLabel: "Class",
    cancel: "Cancel",
    save: "Save",
    appLanguage: "App Language",
    arabic: "العربية 🇹🇳",
    french: "Français 🇫🇷",
    english: "English 🇬🇧",
    signOut: "Sign Out",
    linkChild: "Link Another Student",
    selectLanguageTitle: "Select App Language",
    confirm: "Confirm",
    monday: "Mon",
    tuesday: "Tue",
    wednesday: "Wed",
    thursday: "Thu",
    friday: "Fri",
    saturday: "Sat",
    sunday: "Sun",
    jan: "Jan",
    feb: "Feb",
    mar: "Mar",
    apr: "Apr",
    may: "May",
    jun: "Jun",
    jul: "Jul",
    aug: "Aug",
    sep: "Sep",
    oct: "Oct",
    nov: "Nov",
    dec: "Dec",
    teacherMySchedule: "My Schedule",
    teacherTasks: "Tasks",
    teacherClasses: "Classes",
    teacherUpcomingClasses: "Upcoming Classes",
    teacherNoClassesToday: "No classes scheduled today",
    teacherMarkAttendance: "Mark Attendance",
    teacherViewTasks: "View Tasks",
    teacherQuickActions: "Quick Actions",
    teacherClassesRoster: "Classes · Student Roster",
    teacherAllClasses: "All Classes",
    teacherActiveClasses: "active classes",
    teacherStudentsTotal: "students total",
    teacherLessons: "lessons",
    teacherNoClassesFound: "No classes found",
    teacherClassRoster: "Class Roster",
    teacherStudent: "Student",
    teacherStudents: "Students",
    teacherAttendance: "Attendance",
    teacherGrades: "Grades",
    teacherContact: "Contact",
    teacherTakeAttendance: "Take Attendance",
    teacherPresent: "Present",
    teacherAbsent: "Absent",
    teacherLate: "Late",
    teacherMarkAllPresent: "Mark all Present",
    teacherSubmitAttendance: "Submit Attendance",
    teacherTotalStudents: "Total Students",
    teacherAttendanceSummary: "Summary",
    teacherLessonsContent: "Lessons & Content",
    teacherUploadLesson: "Upload Lesson",
    teacherFiles: "Files",
    teacherDelete: "Delete",
    teacherAddDocument: "Add Document",
    teacherClassTasks: "Class Tasks",
    teacherPending: "Pending",
    teacherGraded: "Graded",
    teacherNoTasksFound: "No tasks found",
    teacherAddTask: "Add Task",
    teacherDue: "Due",
    teacherTaskDetails: "Task Details",
    teacherDescription: "Description",
    teacherAttachments: "Attachments",
    teacherSubmissions: "Submissions",
    teacherGrade: "Grade",
    teacherNoSubmissionsYet: "No submissions yet",
    teacherSubmissionReview: "Submission Review",
    teacherStudentWork: "Student Work",
    teacherAddFeedback: "Add Feedback",
    teacherNoFilesAttached: "No files attached",
    teacherGradeStudent: "Grade Student",
    teacherEnterGrade: "Enter Grade",
    teacherMax20: "Max 20",
    teacherSaveGrade: "Save Grade",
    teacherQuickAssistants: "Quick Assistants",
    teacherOutOf20: "out of 20",
    teacherResetGrade: "Reset",
    welcome: "Welcome",
    pleaseSelectYourProfileTo: "Please select your profile to continue to your account",
    parent: "Parent",
    monitorProgressGradesAndSchool: "Monitor progress, grades, and school schedule.",
    manageLessonsAttendanceAndStudent: "Manage lessons, attendance, and student performance.",
    student: "Student",
    permissionsRequired: "Permissions Required",
    pleaseEnablePushNotificationPermissions: "Please enable push notification permissions in system settings to receive alerts.",
    ok: "OK",
    notificationsEnabled: "Notifications Enabled 🔔",
    youWillNowReceiveInstant: "You will now receive instant push alerts for homework, grades, and school news.",
    ok1: "OK",
    notificationsDisabled: "Notifications Disabled",
    pushNotificationsHaveBeenDisabled: "Push notifications have been disabled.",
    ok2: "OK",
    pleaseEnterYourPhoneNumber: "Please enter your phone number.",
    welcomeBack: "Welcome back!",
    createYourPassword: "Create your password",
    enterYourRegisteredPhoneNumber: "Enter your registered phone number",
    chooseAStrongPasswordFor: "Choose a strong password for your first login",
    continue: "Continue",
    setPassword: "Set Password",
    signIn: "Sign In",
    parentPortal: "PARENT PORTAL",
    teacherPortal: "TEACHER PORTAL",
    accountNotFoundPleaseContact: "Account not found. Please contact support.",
    networkErrorPleaseTryAgain: "Network error. Please try again.",
    pleaseEnterYourPassword: "Please enter your password.",
    passwordSetPleaseSignIn: "Password set! Please sign in.",
    accountResetByAdminPlease: "Account reset by admin. Please choose a new password.",
    authenticationFailedPleaseCheckYour: "Authentication failed. Please check your connection.",
    eg55666777: "e.g. 55 666 777",
    createAStrongPassword: "Create a strong password",
    yourPassword: "Your password",
    accountManagementHandledBySnapschool: "Account management handled by SnapSchool Admin.",
    submission: "Submission",
    completed: "Completed",
    submitted: "Submitted",
    at: "at",
    workSubmitted: "Work Submitted",
    pdfDocument: "PDF Document",
    tapToExpand: "Tap to expand",
    noPhotoSubmitted: "No photo submitted",
    participationScore: "Participation Score",
    quickTags: "Quick Tags",
    addADetailedNote: "Add a detailed note...",
    selectClass: "Select Class",
    tapToSwitch: "Tap to switch",
    selectSession: "Select Session",
    assignATask: "Assign a Task",
    forTheWholeClass: "For the whole class",
    taskTitle: "Task Title",
    descriptionOptional: "Description (optional)",
    addImage: "Add Image",
    addPdf: "Add PDF",
    assignedTasks: "Assigned Tasks",
    saveChanges: "Save Changes",
    switchClass: "Switch Class",
    selectSession1: "Select Session",
    noStudents: "No students",
    variousSubjects: "Various subjects",
    searchClassesOrStudents: "Search classes or students...",
    gradeEntry: "Grade Entry",
    selectClassToRecordEvaluations: "Select class to record evaluations",
    yourClasses: "Your Classes",
    available: "Available",
    noClassesAssigned: "No classes assigned",
    studentsEnrolled: "students enrolled",
    selectSubjectTerm: "Select Subject & Term",
    selectTerm: "Select Term",
    availableSubjects: "Available Subjects",
    gradeEntry1: "Grade Entry",
    graded: "graded",
    quickDecimalAssistant: "Quick Decimal Assistant",
    clear: "Clear",
    gradeSheetProofOptional: "Grade Sheet Proof (Optional)",
    proofImageAttached: "Proof Image attached",
    camera: "Camera",
    gallery: "Gallery",
    saveGrades: "Save Grades",
    enus: "en-US",
    goodMorning: "Good morning 👋",
    seeAll: "See all",
    room: "Room",
    completed1: "Completed",
    live: "Live",
    enus1: "en-US",
    selectClass1: "Select Class",
    tapToSwitch1: "Tap to switch",
    addMaterial: "Add Material",
    title: "Title *",
    egChapter3Notes: "e.g. Chapter 3 Notes",
    subject: "Subject *",
    targetClass: "Target Class",
    descriptionOptional1: "Description (optional)",
    briefDescriptionOfThisMaterial: "Brief description of this material...",
    attachFilesOrImages: "Attach Files or Images",
    uploadShare: "Upload & Share",
    allSubjects: "All Subjects",
    noMaterialsYet: "No Materials Yet",
    uploadPdfsNotesOrLinks: "Upload PDFs, notes, or links for your students to access.",
    addMaterial1: "Add Material",
    file: "file",
    files: "files",
    switchClass1: "Switch Class",
    filterBySubject: "Filter by Subject",
    overallProgress: "Overall Progress",
    completed2: "completed",
    noSubmissionsYet: "No submissions yet",
    taskDetailsAttachments: "Task Details & Attachments",
    noDescriptionProvided: "No description provided",
    photoAttached: "Photo Attached",
    documentAttached: "Document Attached",
    noAttachments: "No attachments",
    submissions: "Submissions",
    students: "students",
    completed3: "completed",
    createNewTask: "Create New Task",
    title1: "Title",
    egMathQuizHistoryEssay: "e.g. Math Quiz, History Essay",
    description: "Description",
    detailsAboutTheTask: "Details about the task...",
    class: "Class",
    attachments: "Attachments",
    addImagesMax5: "Add Images (Max 5)",
    createTask: "Create Task",
    selectClass2: "Select Class",
    tapToSwitch2: "Tap to switch",
    noActiveTasksFound: "No active tasks found",
    switchClass2: "Switch Class",
    standard: "Standard",
    lateWord: "Late",
    absentWord: "Absent",
    presentWord: "Present",
    markedAs: "marked as",
    forWord: "for",
    notifPaymentAlert: "Payment Alert",
    notifNewAssignment: "New Assignment",
    notifSchoolAnnouncement: "School Announcement",
    deleteBtn: "Delete",
    notifAbsences: "Absences",
    older: "Older",
    today: "Today",
    yesterday: "Yesterday",
    notificationsScreenTitle: "Notifications",
    markAllAsRead: "Mark all as read",
    filterUnread: "Unread",
    filterUrgent: "Urgent",
    notifDefaultTitle: "Notification",
    notifTeacherRemark: "Teacher Remark",
    notifAttendanceUpdate: "Attendance Update",
    completedTask: "Completed",
    pendingTask: "Pending",
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => Promise<void>;
  t: typeof translations['ar'];
  isRTL: boolean;
  getTranslatedSubject: (rawName: string | null | undefined) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'ar',
  setLanguage: async () => {},
  t: translations.ar,
  isRTL: true,
  getTranslatedSubject: () => '',
});

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLangState] = useState<Language>('ar');

  useEffect(() => {
    AsyncStorage.getItem(LANGUAGE_KEY).then((stored) => {
      if (stored && (stored === 'ar' || stored === 'fr' || stored === 'en')) {
        setLangState(stored as Language);
      }
    });
  }, []);

  const setLanguage = async (newLang: Language) => {
    setLangState(newLang);
    await AsyncStorage.setItem(LANGUAGE_KEY, newLang);
  };

  const getTranslatedSubject = (rawName: string | null | undefined): string => {
    if (!rawName) return '';
    const parts = rawName.split('|').map((p) => p.trim());
    if (parts.length >= 3) {
      if (language === 'ar') return parts[0];
      if (language === 'fr') return parts[1];
      return parts[2];
    }
    return parts[0];
  };

  const t = translations[language] || translations.ar;
  const isRTL = language === 'ar';

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL, getTranslatedSubject }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
